name: all_in_one_music_player
description: Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_links: 2.2.2
  audio_service: ^0.18.8
  audiotagger:
    git:
      url: https://github.com/Sangwan5688/Audiotagger
      ref: 90f2db5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^8.0.0
  file_picker: ^5.2.4
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_displaymode: ^0.5.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.30
  logging: ^1.1.0
  marquee: ^2.2.3
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.6.1
  package_info_plus: ^3.0.2
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  receive_sharing_intent: ^1.4.5
  salomon_bottom_bar: ^3.3.1
  share_plus: ^6.3.0
  sliding_up_panel: ^2.0.0+1
  supabase: ^1.1.1
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

# flutter_test:
#   sdk: flutter
#   lint: ^1.10.0
#   msix: ^3.6.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
    
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/
    - assets/icon/

flutter_native_splash:
  color: "#001736"
  image: "assets/icon/icon.png"

msix_config:
  display_name: All In One Music Player
  publisher_display_name: Syed Arsalan Kazmi
  identity_name: com.verox.allinonemusicplayer
  icons_background_color: transparent
  logo_path: "assets/icon/icon.png"
  file_extension: .mp3, .m4a
